auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  ingestion_rate_mb: 256
  ingestion_burst_size_mb: 512
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 72h

  otlp_config:
    resource_attributes:
      attributes_config:
        - action: index_label
          attributes:
            - node.name
            - component.name
            - process.name
            - akernel_env
            - adx_env

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/storage

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
