apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prometheusServer.persistence.claimName | default "prometheus-pvc-ssd" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheusServer.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.prometheusServer.persistence.size }}
  storageClassName: {{ .Values.prometheusServer.persistence.storageClass }}
  volumeMode: Filesystem
